SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


INSERT INTO `algo` (`iId`, `snake`, `type`, `color`, `headshape`, `texture`, `eyeshape`, `symptoms`, `dCreatedDate`, `vStatus`) VALUES
(1, 'cobra', 'venomous', 'black', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'redness', '0000-00-00 00:00:00', '1'),
(2, 'cobra', 'venomous', 'black', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(3, 'cobra', 'venomous', 'black', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'severe pain', '0000-00-00 00:00:00', '1'),
(4, 'cobra', 'venomous', 'black', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'breathing problem', '0000-00-00 00:00:00', '1'),
(5, 'cobra', 'venomous', 'black', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'vomiting', '0000-00-00 00:00:00', '1'),
(6, 'cobra', 'venomous', 'black', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'kidney failure', '0000-00-00 00:00:00', '1'),
(7, 'cobra', 'venomous', 'dark brown', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'redness', '0000-00-00 00:00:00', '1'),
(8, 'cobra', 'venomous', 'dark brown', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(9, 'cobra', 'venomous', 'dark brown', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'severe pain', '0000-00-00 00:00:00', '1'),
(10, 'cobra', 'venomous', 'dark brown', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'breathing problem', '0000-00-00 00:00:00', '1'),
(11, 'cobra', 'venomous', 'dark brown', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'vomiting', '0000-00-00 00:00:00', '1'),
(12, 'cobra', 'venomous', 'dark brown', 'triangular spade shaped', 'Body color is yellowish white', 'round', 'kidney failure', '0000-00-00 00:00:00', '1'),
(13, 'king cobra', 'venomous', 'yellow', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'blurred vision', '0000-00-00 00:00:00', '1'),
(14, 'king cobra', 'venomous', 'yellow', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'speech problem', '0000-00-00 00:00:00', '1'),
(15, 'king cobra', 'venomous', 'yellow', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'sudden loss of consciousness', '0000-00-00 00:00:00', '1'),
(16, 'king cobra', 'venomous', 'yellow', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'headache', '0000-00-00 00:00:00', '1'),
(17, 'king cobra', 'venomous', 'yellow', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(18, 'king cobra', 'venomous', 'green', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'blurred vision', '0000-00-00 00:00:00', '1'),
(19, 'king cobra', 'venomous', 'green', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'speech problem', '0000-00-00 00:00:00', '1'),
(20, 'king cobra', 'venomous', 'green', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'sudden loss of consciousness', '0000-00-00 00:00:00', '1'),
(21, 'king cobra', 'venomous', 'green', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'headache', '0000-00-00 00:00:00', '1'),
(22, 'king cobra', 'venomous', 'green', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(23, 'king cobra', 'venomous', 'brown black white crossbars', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'blurred vision', '0000-00-00 00:00:00', '1'),
(24, 'king cobra', 'venomous', 'brown black white crossbars', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'speech problem', '0000-00-00 00:00:00', '1'),
(25, 'king cobra', 'venomous', 'brown black white crossbars', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'sudden loss of consciousness', '0000-00-00 00:00:00', '1'),
(26, 'king cobra', 'venomous', 'brown black white crossbars', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'headache', '0000-00-00 00:00:00', '1'),
(27, 'king cobra', 'venomous', 'brown black white crossbars', 'roughly wedged shaped head broad and flattened', 'chevron pattern on back', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(28, 'saw scaled viper', 'venomous', 'pale buff', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'blood clothing', '0000-00-00 00:00:00', '1'),
(29, 'saw scaled viper', 'venomous', 'pale buff', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'abdominal pain', '0000-00-00 00:00:00', '1'),
(30, 'saw scaled viper', 'venomous', 'pale buff', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'vomiting', '0000-00-00 00:00:00', '1'),
(31, 'saw scaled viper', 'venomous', 'pale buff', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'kidney failure', '0000-00-00 00:00:00', '1'),
(32, 'saw scaled viper', 'venomous', 'pale buff', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'internal bleeding', '0000-00-00 00:00:00', '1'),
(33, 'saw scaled viper', 'venomous', 'greyish', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'blood clothing', '0000-00-00 00:00:00', '1'),
(34, 'saw scaled viper', 'venomous', 'greyish', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'abdominal pain', '0000-00-00 00:00:00', '1'),
(35, 'saw scaled viper', 'venomous', 'greyish', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'vomiting', '0000-00-00 00:00:00', '1'),
(36, 'saw scaled viper', 'venomous', 'greyish', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'kidney failure', '0000-00-00 00:00:00', '1'),
(37, 'saw scaled viper', 'venomous', 'greyish', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'internal bleeding', '0000-00-00 00:00:00', '1'),
(38, 'saw scaled viper', 'venomous', 'olive', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'blood clothing', '0000-00-00 00:00:00', '1'),
(39, 'saw scaled viper', 'venomous', 'olive', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'abdominal pain', '0000-00-00 00:00:00', '1'),
(40, 'saw scaled viper', 'venomous', 'olive', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'vomiting', '0000-00-00 00:00:00', '1'),
(41, 'saw scaled viper', 'venomous', 'olive', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'kidney failure', '0000-00-00 00:00:00', '1'),
(42, 'saw scaled viper', 'venomous', 'olive', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'internal bleeding', '0000-00-00 00:00:00', '1'),
(43, 'saw scaled viper', 'venomous', 'pale brown', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'blood clothing', '0000-00-00 00:00:00', '1'),
(44, 'saw scaled viper', 'venomous', 'pale brown', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'abdominal pain', '0000-00-00 00:00:00', '1'),
(45, 'saw scaled viper', 'venomous', 'pale brown', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'vomiting', '0000-00-00 00:00:00', '1'),
(46, 'saw scaled viper', 'venomous', 'pale brown', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'kidney failure', '0000-00-00 00:00:00', '1'),
(47, 'saw scaled viper', 'venomous', 'pale brown', 'pear shaped', 'whitish spots edged with dark brown', 'elliptical', 'internal bleeding', '0000-00-00 00:00:00', '1'),
(48, 'russel viper', 'venomous', 'yellow', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'severe pain', '0000-00-00 00:00:00', '1'),
(49, 'russel viper', 'venomous', 'yellow', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'swelling', '0000-00-00 00:00:00', '1'),
(50, 'russel viper', 'venomous', 'yellow', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'lower back pain', '0000-00-00 00:00:00', '1'),
(51, 'russel viper', 'venomous', 'yellow', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'feeling sleepy', '0000-00-00 00:00:00', '1'),
(52, 'russel viper', 'venomous', 'yellow', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'bleeding from distant sites', '0000-00-00 00:00:00', '1'),
(53, 'russel viper', 'venomous', 'yellow', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'vomiting', '0000-00-00 00:00:00', '1'),
(54, 'russel viper', 'venomous', 'tan', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'severe pain', '0000-00-00 00:00:00', '1'),
(55, 'russel viper', 'venomous', 'tan', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'swelling', '0000-00-00 00:00:00', '1'),
(56, 'russel viper', 'venomous', 'tan', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'lower back pain', '0000-00-00 00:00:00', '1'),
(57, 'russel viper', 'venomous', 'tan', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'feeling sleepy', '0000-00-00 00:00:00', '1'),
(58, 'russel viper', 'venomous', 'tan', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'bleeding from distant sites', '0000-00-00 00:00:00', '1'),
(59, 'russel viper', 'venomous', 'tan', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'vomiting', '0000-00-00 00:00:00', '1'),
(60, 'russel viper', 'venomous', 'brown', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'severe pain', '0000-00-00 00:00:00', '1'),
(61, 'russel viper', 'venomous', 'brown', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'swelling', '0000-00-00 00:00:00', '1'),
(62, 'russel viper', 'venomous', 'brown', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'lower back pain', '0000-00-00 00:00:00', '1'),
(63, 'russel viper', 'venomous', 'brown', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'feeling sleepy', '0000-00-00 00:00:00', '1'),
(64, 'russel viper', 'venomous', 'brown', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'bleeding from distant sites', '0000-00-00 00:00:00', '1'),
(65, 'russel viper', 'venomous', 'brown', 'flattened and triangular', 'three series of dark brown spots on the body surrounded by black rings', 'elliptical', 'vomiting', '0000-00-00 00:00:00', '1'),
(66, 'common krait', 'venomous', 'black', 'flattened', 'white crossbars', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(67, 'common krait', 'venomous', 'black', 'flattened', 'white crossbars', 'round', 'abdominal pain', '0000-00-00 00:00:00', '1'),
(68, 'common krait', 'venomous', 'black', 'flattened', 'white crossbars', 'round', 'vomiting', '0000-00-00 00:00:00', '1'),
(69, 'common krait', 'venomous', 'black', 'flattened', 'white crossbars', 'round', 'facial paralysis', '0000-00-00 00:00:00', '1'),
(70, 'common krait', 'venomous', 'black', 'flattened', 'white crossbars', 'round', 'headache', '0000-00-00 00:00:00', '1'),
(71, 'common krait', 'venomous', 'bluish black', 'flattened', 'white crossbars', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(72, 'common krait', 'venomous', 'bluish black', 'flattened', 'white crossbars', 'round', 'abdominal pain', '0000-00-00 00:00:00', '1'),
(73, 'common krait', 'venomous', 'bluish black', 'flattened', 'white crossbars', 'round', 'vomiting', '0000-00-00 00:00:00', '1'),
(74, 'common krait', 'venomous', 'bluish black', 'flattened', 'white crossbars', 'round', 'facial paralysis', '0000-00-00 00:00:00', '1'),
(75, 'common krait', 'venomous', 'bluish black', 'flattened', 'white crossbars', 'round', 'headache', '0000-00-00 00:00:00', '1'),
(76, 'bamboo pit viper', 'venomous', 'bright green', 'triangular', 'tail is red or yellow in color', 'vertical', 'immediate pain with rapid swelling', '0000-00-00 00:00:00', '1'),
(77, 'bamboo pit viper', 'venomous', 'bright green', 'triangular', 'tail is red or yellow in color', 'vertical', 'swelling in lymph nodes near the bite', '0000-00-00 00:00:00', '1'),
(78, 'bamboo pit viper', 'venomous', 'bright green', 'triangular', 'tail is red or yellow in color', 'vertical', 'changes in heart rate ', '0000-00-00 00:00:00', '1'),
(79, 'bamboo pit viper', 'venomous', 'bright green', 'triangular', 'tail is red or yellow in color', 'vertical', 'breathing problem', '0000-00-00 00:00:00', '1'),
(80, 'bamboo pit viper', 'venomous', 'yellow', 'triangular', 'tail is red or yellow in color', 'vertical', 'immediate pain with rapid swelling', '0000-00-00 00:00:00', '1'),
(81, 'bamboo pit viper', 'venomous', 'yellow', 'triangular', 'tail is red or yellow in color', 'vertical', 'sign of shock', '0000-00-00 00:00:00', '1'),
(82, 'bamboo pit viper', 'venomous', 'yellow', 'triangular', 'tail is red or yellow in color', 'vertical', 'swelling in lymph nodes near the bite', '0000-00-00 00:00:00', '1'),
(83, 'bamboo pit viper', 'venomous', 'yellow', 'triangular', 'tail is red or yellow in color', 'vertical', 'changes in heart rate ', '0000-00-00 00:00:00', '1'),
(84, 'bamboo pit viper', 'venomous', 'yellow', 'triangular', 'tail is red or yellow in color', 'vertical', 'breathing problem', '0000-00-00 00:00:00', '1'),
(85, 'bamboo pit viper', 'venomous', 'greyish', 'triangular', 'tail is red or yellow in color', 'vertical', 'immediate pain with rapid swelling', '0000-00-00 00:00:00', '1'),
(86, 'bamboo pit viper', 'venomous', 'greyish', 'triangular', 'tail is red or yellow in color', 'vertical', 'sign of shock', '0000-00-00 00:00:00', '1'),
(87, 'bamboo pit viper', 'venomous', 'greyish', 'triangular', 'tail is red or yellow in color', 'vertical', 'swelling in lymph nodes near the bite', '0000-00-00 00:00:00', '1'),
(88, 'bamboo pit viper', 'venomous', 'greyish', 'triangular', 'tail is red or yellow in color', 'vertical', 'changes in heart rate ', '0000-00-00 00:00:00', '1'),
(89, 'bamboo pit viper', 'venomous', 'greyish', 'triangular', 'tail is red or yellow in color', 'vertical', 'breathing problem', '0000-00-00 00:00:00', '1'),
(90, 'bamboo pit viper', 'venomous', 'purplish brown', 'triangular', 'tail is red or yellow in color', 'vertical', 'immediate pain with rapid swelling', '0000-00-00 00:00:00', '1'),
(91, 'bamboo pit viper', 'venomous', 'purplish brown', 'triangular', 'tail is red or yellow in color', 'vertical', 'sign of shock', '0000-00-00 00:00:00', '1'),
(92, 'bamboo pit viper', 'venomous', 'purplish brown', 'triangular', 'tail is red or yellow in color', 'vertical', 'swelling in lymph nodes near the bite', '0000-00-00 00:00:00', '1'),
(93, 'bamboo pit viper', 'venomous', 'purplish brown', 'triangular', 'tail is red or yellow in color', 'vertical', 'changes in heart rate ', '0000-00-00 00:00:00', '1'),
(94, 'bamboo pit viper', 'venomous', 'purplish brown', 'triangular', 'tail is red or yellow in color', 'vertical', 'breathing problem', '0000-00-00 00:00:00', '1'),
(95, 'malabar pit viper', 'venomous', 'pale green', 'triangular', 'triangular shaped head with heat sensing pit organs', 'vertically elliptical', 'Severe pain', '0000-00-00 00:00:00', '1'),
(96, 'hump nosed pit viper', 'venomous', 'light brown', 'a wide head the snout is pointed and turned upwards ending in a hump', 'light brown with a double row of darker brown patches along the back', 'vertical', 'sign of shock', '0000-00-00 00:00:00', '1'),
(97, 'hump nosed pit viper', 'venomous', 'light brown', 'a wide head the snout is pointed and turned upwards ending in a hump', 'light brown with a double row of darker brown patches along the back', 'vertical', 'vomiting', '0000-00-00 00:00:00', '1'),
(98, 'hump nosed pit viper', 'venomous', 'light brown', 'a wide head the snout is pointed and turned upwards ending in a hump', 'light brown with a double row of darker brown patches along the back', 'vertical', 'abdominal pain', '0000-00-00 00:00:00', '1'),
(99, 'hump nosed pit viper', 'venomous', 'light brown', 'a wide head the snout is pointed and turned upwards ending in a hump', 'light brown with a double row of darker brown patches along the back', 'vertical', 'diarrhea', '0000-00-00 00:00:00', '1'),
(100, 'striped coral snake', 'venomous', 'warm red', 'curved', 'strips with different color patterns', 'round', 'vomiting', '0000-00-00 00:00:00', '1'),
(101, 'striped coral snake', 'venomous', 'warm red', 'curved', 'strips with different color patterns', 'round', 'paralysis', '0000-00-00 00:00:00', '1'),
(102, 'striped coral snake', 'venomous', 'warm red', 'curved', 'strips with different color patterns', 'round', 'muscle twitching', '0000-00-00 00:00:00', '1'),
(103, 'striped coral snake', 'venomous', 'warm red', 'curved', 'strips with different color patterns', 'round', 'feeling sleepy', '0000-00-00 00:00:00', '1'),
(104, 'striped coral snake', 'venomous', 'warm red', 'curved', 'strips with different color patterns', 'round', 'double vision', '0000-00-00 00:00:00', '1'),
(105, 'striped coral snake', 'venomous', 'warm red', 'curved', 'strips with different color patterns', 'round', 'abnormal sensations', '0000-00-00 00:00:00', '1'),
(106, 'striped coral snake', 'venomous', 'reddish orange', 'curved', 'strips with different color patterns', 'round', 'vomiting', '0000-00-00 00:00:00', '1'),
(107, 'striped coral snake', 'venomous', 'reddish orange', 'curved', 'strips with different color patterns', 'round', 'paralysis', '0000-00-00 00:00:00', '1'),
(108, 'striped coral snake', 'venomous', 'reddish orange', 'curved', 'strips with different color patterns', 'round', 'muscle twitching', '0000-00-00 00:00:00', '1'),
(109, 'striped coral snake', 'venomous', 'reddish orange', 'curved', 'strips with different color patterns', 'round', 'feeling sleepy', '0000-00-00 00:00:00', '1'),
(110, 'striped coral snake', 'venomous', 'reddish orange', 'curved', 'strips with different color patterns', 'round', 'double vision', '0000-00-00 00:00:00', '1'),
(111, 'striped coral snake', 'venomous', 'reddish orange', 'curved', 'strips with different color patterns', 'round', 'abnormal sensations', '0000-00-00 00:00:00', '1'),
(112, 'short sea snake', 'venomous', 'black with grey rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'dizziness', '0000-00-00 00:00:00', '1'),
(113, 'short sea snake', 'venomous', 'black with grey rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(114, 'short sea snake', 'venomous', 'black with grey rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'coma', '0000-00-00 00:00:00', '1'),
(115, 'short sea snake', 'venomous', 'black with grey rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'altered mental status', '0000-00-00 00:00:00', '1'),
(116, 'short sea snake', 'venomous', 'black with grey rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'speech problem', '0000-00-00 00:00:00', '1'),
(117, 'short sea snake', 'venomous', 'black with grey rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'weakness', '0000-00-00 00:00:00', '1'),
(118, 'short sea snake', 'venomous', 'black with blue rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'dizziness', '0000-00-00 00:00:00', '1'),
(119, 'short sea snake', 'venomous', 'black with blue rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(120, 'short sea snake', 'venomous', 'black with blue rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'coma', '0000-00-00 00:00:00', '1'),
(121, 'short sea snake', 'venomous', 'black with blue rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'altered mental status', '0000-00-00 00:00:00', '1'),
(122, 'short sea snake', 'venomous', 'black with blue rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'speech problem', '0000-00-00 00:00:00', '1'),
(123, 'short sea snake', 'venomous', 'black with blue rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'weakness', '0000-00-00 00:00:00', '1'),
(124, 'short sea snake', 'venomous', 'black with white rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'dizziness', '0000-00-00 00:00:00', '1'),
(125, 'short sea snake', 'venomous', 'black with white rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'respiratory paralysis', '0000-00-00 00:00:00', '1'),
(126, 'short sea snake', 'venomous', 'black with white rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'coma', '0000-00-00 00:00:00', '1'),
(127, 'short sea snake', 'venomous', 'black with white rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'altered mental status', '0000-00-00 00:00:00', '1'),
(128, 'short sea snake', 'venomous', 'black with white rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'speech problem', '0000-00-00 00:00:00', '1'),
(129, 'short sea snake', 'venomous', 'black with white rings', 'triangular', 'flattened body with a short oarlike tail', 'round', 'weakness', '0000-00-00 00:00:00', '1'),
(130, 'nosed sea snake', 'venomous', 'greyish green', 'broad', 'flattened body with a short oarlike tail', 'round', 'muscle twitching', '0000-00-00 00:00:00', '1'),
(131, 'nosed sea snake', 'venomous', 'greyish green', 'broad', 'flattened body with a short oarlike tail', 'round', 'blurred vision', '0000-00-00 00:00:00', '1'),
(132, 'nosed sea snake', 'venomous', 'greyish green', 'broad', 'flattened body with a short oarlike tail', 'round', 'joint aches', '0000-00-00 00:00:00', '1'),
(133, 'nosed sea snake', 'venomous', 'greyish green', 'broad', 'flattened body with a short oarlike tail', 'round', 'paralysis legs', '0000-00-00 00:00:00', '1'),
(134, 'common vine snake', 'mildly venomous', 'green', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'swelling', '0000-00-00 00:00:00', '1'),
(135, 'common vine snake', 'mildly venomous', 'green', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'numbness', '0000-00-00 00:00:00', '1'),
(136, 'common vine snake', 'mildly venomous', 'green', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'bruising', '0000-00-00 00:00:00', '1'),
(137, 'common vine snake', 'mildly venomous', 'green', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'severe pain', '0000-00-00 00:00:00', '1'),
(138, 'common vine snake', 'mildly venomous', 'greyish', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'swelling', '0000-00-00 00:00:00', '1'),
(139, 'common vine snake', 'mildly venomous', 'greyish', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'numbness', '0000-00-00 00:00:00', '1'),
(140, 'common vine snake', 'mildly venomous', 'greyish', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'bruising', '0000-00-00 00:00:00', '1'),
(141, 'common vine snake', 'mildly venomous', 'greyish', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'severe pain', '0000-00-00 00:00:00', '1'),
(142, 'common vine snake', 'mildly venomous', 'brown', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'swelling', '0000-00-00 00:00:00', '1'),
(143, 'common vine snake', 'mildly venomous', 'brown', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'numbness', '0000-00-00 00:00:00', '1'),
(144, 'common vine snake', 'mildly venomous', 'brown', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'bruising', '0000-00-00 00:00:00', '1'),
(145, 'common vine snake', 'mildly venomous', 'brown', 'narrow head and pointed snout', 'black and white scale marking', 'horizontal', 'severe pain', '0000-00-00 00:00:00', '1'),
(146, 'ornate flying snake', 'mildly venomous', 'green', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(147, 'ornate flying snake', 'mildly venomous', 'green', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'bleeding', '0000-00-00 00:00:00', '1'),
(148, 'ornate flying snake', 'mildly venomous', 'green', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'paresthesia', '0000-00-00 00:00:00', '1'),
(149, 'ornate flying snake', 'mildly venomous', 'green', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'bruising', '0000-00-00 00:00:00', '1'),
(150, 'ornate flying snake', 'mildly venomous', 'green', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'severe pain', '0000-00-00 00:00:00', '1'),
(151, 'ornate flying snake', 'mildly venomous', 'brown', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(152, 'ornate flying snake', 'mildly venomous', 'brown', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'bleeding', '0000-00-00 00:00:00', '1'),
(153, 'ornate flying snake', 'mildly venomous', 'brown', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'paresthesia', '0000-00-00 00:00:00', '1'),
(154, 'ornate flying snake', 'mildly venomous', 'brown', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'bruising', '0000-00-00 00:00:00', '1'),
(155, 'ornate flying snake', 'mildly venomous', 'brown', 'flattened', 'black cross hatching yellow or gold color accents', 'round', 'severe pain', '0000-00-00 00:00:00', '1'),
(156, 'common cat snake', 'mildly venomous', 'greyish brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'swelling', '0000-00-00 00:00:00', '1'),
(157, 'common cat snake', 'mildly venomous', 'greyish brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'coma', '0000-00-00 00:00:00', '1'),
(158, 'common cat snake', 'mildly venomous', 'greyish brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'blood in urine', '0000-00-00 00:00:00', '1'),
(159, 'common cat snake', 'mildly venomous', 'greyish brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'breathing problem', '0000-00-00 00:00:00', '1'),
(160, 'common cat snake', 'mildly venomous', 'greyish brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'diarrhea', '0000-00-00 00:00:00', '1'),
(161, 'common cat snake', 'mildly venomous', 'brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'swelling', '0000-00-00 00:00:00', '1'),
(162, 'common cat snake', 'mildly venomous', 'brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'coma', '0000-00-00 00:00:00', '1'),
(163, 'common cat snake', 'mildly venomous', 'brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'blood in urine', '0000-00-00 00:00:00', '1'),
(164, 'common cat snake', 'mildly venomous', 'brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'breathing problem', '0000-00-00 00:00:00', '1'),
(165, 'common cat snake', 'mildly venomous', 'brown', 'triangular', 'lighter zig zag patterns over the body', 'narrow vertical slits', 'diarrhea', '0000-00-00 00:00:00', '1'),
(166, 'ceylon cat snake', 'mildly venomous', 'brown mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'swelling', '0000-00-00 00:00:00', '1'),
(167, 'ceylon cat snake', 'mildly venomous', 'brown mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'paralysis', '0000-00-00 00:00:00', '1'),
(168, 'ceylon cat snake', 'mildly venomous', 'brown mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'blood in urine', '0000-00-00 00:00:00', '1'),
(169, 'ceylon cat snake', 'mildly venomous', 'brown mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'breathing problem', '0000-00-00 00:00:00', '1'),
(170, 'ceylon cat snake', 'mildly venomous', 'brown mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'diarrhea', '0000-00-00 00:00:00', '1'),
(171, 'ceylon cat snake', 'mildly venomous', 'yellowish  mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'swelling', '0000-00-00 00:00:00', '1'),
(172, 'ceylon cat snake', 'mildly venomous', 'yellowish  mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'paralysis', '0000-00-00 00:00:00', '1'),
(173, 'ceylon cat snake', 'mildly venomous', 'yellowish  mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'blood in urine', '0000-00-00 00:00:00', '1'),
(174, 'ceylon cat snake', 'mildly venomous', 'yellowish  mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'breathing problem', '0000-00-00 00:00:00', '1'),
(175, 'ceylon cat snake', 'mildly venomous', 'yellowish  mixed with reddish', 'triangular', 'cross lines found from head to tail', 'vertical', 'diarrhea', '0000-00-00 00:00:00', '1'),
(176, 'forsten cat snake', 'mildly venomous', 'greyish', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'swelling', '0000-00-00 00:00:00', '1'),
(177, 'forsten cat snake', 'mildly venomous', 'greyish', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'severe pain', '0000-00-00 00:00:00', '1'),
(178, 'forsten cat snake', 'mildly venomous', 'greyish', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'vomiting', '0000-00-00 00:00:00', '1'),
(179, 'forsten cat snake', 'mildly venomous', 'greyish', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'nausea', '0000-00-00 00:00:00', '1'),
(180, 'forsten cat snake', 'mildly venomous', 'greyish', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'bruising', '0000-00-00 00:00:00', '1'),
(181, 'forsten cat snake', 'mildly venomous', 'brown', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'swelling', '0000-00-00 00:00:00', '1'),
(182, 'forsten cat snake', 'mildly venomous', 'brown', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'severe pain', '0000-00-00 00:00:00', '1'),
(183, 'forsten cat snake', 'mildly venomous', 'brown', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'vomiting', '0000-00-00 00:00:00', '1'),
(184, 'forsten cat snake', 'mildly venomous', 'brown', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'nausea', '0000-00-00 00:00:00', '1'),
(185, 'forsten cat snake', 'mildly venomous', 'brown', 'triangular', 'black and yellowish white zig zag markings on the body', 'vertical', 'bruising', '0000-00-00 00:00:00', '1'),
(186, 'brown vine snake', 'mildly venomous', 'green', 'sharply triangular', 'black spots throughout body with underneath color white', 'horizontal', 'no symptoms', '0000-00-00 00:00:00', '1'),
(187, 'brown vine snake', 'mildly venomous', 'grey brown', 'sharply triangular', 'black spots throughout body with underneath color white', 'horizontal', 'no symptoms', '0000-00-00 00:00:00', '1'),
(188, 'beddoms cat snake', 'mildly venomous', 'brown', 'Supralabial', 'cross lines found from head to tail', 'vertical', 'no symptoms', '0000-00-00 00:00:00', '1'),
(189, 'beddoms cat snake', 'mildly venomous', 'yellowish mixed with reddish', 'Supralabial', 'cross lines found from head to tail', 'vertical', 'no symptoms', '0000-00-00 00:00:00', '1'),
(190, 'beddoms cat snake', 'mildly venomous', 'brown mixed with reddish', 'Supralabial', 'cross lines found from head to tail', 'vertical', 'no symptoms', '0000-00-00 00:00:00', '1'),
(191, 'blind or worm snake', 'non venomous', 'charcoal grey', 'head is same size as body', 'head and tail are superficially similar', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(192, 'blind or worm snake', 'non venomous', 'silver grey', 'head is same size as body', 'head and tail are superficially similar', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(193, 'blind or worm snake', 'non venomous', 'light yellow', 'head is same size as body', 'head and tail are superficially similar', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(194, 'blind or worm snake', 'non venomous', 'purplish', 'head is same size as body', 'head and tail are superficially similar', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(195, 'beaked blind', 'non venomous', 'pink', 'small thin and shiny head', 'tail is tipped with a tiny pointed spur', 'round', 'no bite', '0000-00-00 00:00:00', '1'),
(196, 'whitakers boa', 'non venomous', 'yellowish white with dark patches', 'small head', 'tail is thick and short and ends with a rounded tip', 'vertically elliptical', 'swelling', '0000-00-00 00:00:00', '1'),
(197, 'whitakers boa', 'non venomous', 'yellowish white with dark patches', 'small head', 'tail is thick and short and ends with a rounded tip', 'vertically elliptical', 'redness', '0000-00-00 00:00:00', '1'),
(198, 'whitakers boa', 'non venomous', 'yellowish white without dark patches', 'small head', 'tail is thick and short and ends with a rounded tip', 'vertically elliptical', 'swelling', '0000-00-00 00:00:00', '1'),
(199, 'whitakers boa', 'non venomous', 'yellowish white without dark patches', 'small head', 'tail is thick and short and ends with a rounded tip', 'vertically elliptical', 'redness', '0000-00-00 00:00:00', '1'),
(200, 'indian rock python', 'non venomous', 'whitish', 'arrow shaped marking present on the top of the head', 'whitish or yellowish with blotched patterns', 'vertical', 'several teeth marks in curved shape', '0000-00-00 00:00:00', '1'),
(201, 'indian rock python', 'non venomous', 'whitish', 'arrow shaped marking present on the top of the head', 'whitish or yellowish with blotched patterns', 'vertical', 'sustained a severe hand injury', '0000-00-00 00:00:00', '1'),
(202, 'indian rock python', 'non venomous', 'yellow', 'arrow shaped marking present on the top of the head', 'whitish or yellowish with blotched patterns', 'vertical', 'several teeth marks in curved shape', '0000-00-00 00:00:00', '1'),
(203, 'indian rock python', 'non venomous', 'yellow', 'arrow shaped marking present on the top of the head', 'whitish or yellowish with blotched patterns', 'vertical', 'sustained a severe hand injury', '0000-00-00 00:00:00', '1'),
(204, 'indian rock python', 'non venomous', 'dark brown', 'arrow shaped marking present on the top of the head', 'whitish or yellowish with blotched patterns', 'vertical', 'several teeth marks in curved shape', '0000-00-00 00:00:00', '1'),
(205, 'indian rock python', 'non venomous', 'dark brown', 'arrow shaped marking present on the top of the head', 'whitish or yellowish with blotched patterns', 'vertical', 'sustained a severe hand injury', '0000-00-00 00:00:00', '1'),
(206, 'rat snake', 'non venomous', 'pale yellow', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'redness', '0000-00-00 00:00:00', '1'),
(207, 'rat snake', 'non venomous', 'pale yellow', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'facial paralysis', '0000-00-00 00:00:00', '1'),
(208, 'rat snake', 'non venomous', 'pale yellow', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'increased salivation and sweating', '0000-00-00 00:00:00', '1'),
(209, 'rat snake', 'non venomous', 'pale yellow', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(210, 'rat snake', 'non venomous', 'olive', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'redness', '0000-00-00 00:00:00', '1'),
(211, 'rat snake', 'non venomous', 'olive', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'facial paralysis', '0000-00-00 00:00:00', '1'),
(212, 'rat snake', 'non venomous', 'olive', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'increased salivation and sweating', '0000-00-00 00:00:00', '1'),
(213, 'rat snake', 'non venomous', 'olive', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(214, 'rat snake', 'non venomous', 'brown', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'redness', '0000-00-00 00:00:00', '1'),
(215, 'rat snake', 'non venomous', 'brown', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'facial paralysis', '0000-00-00 00:00:00', '1'),
(216, 'rat snake', 'non venomous', 'brown', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'increased salivation and sweating', '0000-00-00 00:00:00', '1'),
(217, 'rat snake', 'non venomous', 'brown', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(218, 'rat snake', 'non venomous', 'greyish black', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'redness', '0000-00-00 00:00:00', '1'),
(219, 'rat snake', 'non venomous', 'greyish black', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'facial paralysis', '0000-00-00 00:00:00', '1'),
(220, 'rat snake', 'non venomous', 'greyish black', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'increased salivation and sweating', '0000-00-00 00:00:00', '1'),
(221, 'rat snake', 'non venomous', 'greyish black', 'head larger than neck', 'a keeled upper body with underside  prominent dark bands', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(222, 'montane trinket snake', 'non venomous', 'brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'bleeding', '0000-00-00 00:00:00', '1'),
(223, 'montane trinket snake', 'non venomous', 'brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'Itching', '0000-00-00 00:00:00', '1'),
(224, 'montane trinket snake', 'non venomous', 'brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'redness', '0000-00-00 00:00:00', '1'),
(225, 'montane trinket snake', 'non venomous', 'brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'swelling', '0000-00-00 00:00:00', '1'),
(226, 'montane trinket snake', 'non venomous', 'whitish brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'bleeding', '0000-00-00 00:00:00', '1'),
(227, 'montane trinket snake', 'non venomous', 'whitish brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'Itching', '0000-00-00 00:00:00', '1'),
(228, 'montane trinket snake', 'non venomous', 'whitish brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'redness', '0000-00-00 00:00:00', '1'),
(229, 'montane trinket snake', 'non venomous', 'whitish brown', 'somewhat elongated', 'patterns have highest contrast near the head', 'bear round', 'swelling', '0000-00-00 00:00:00', '1'),
(230, 'checkered keelback', 'non venomous', 'olive brown', 'pointed and slightly broader than their neck', 'checkered pattern all over the body in variation of green yellow or black', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(231, 'checkered keelback', 'non venomous', 'olive brown', 'pointed and slightly broader than their neck', 'checkered pattern all over the body in variation of green yellow or black', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(232, 'checkered keelback', 'non venomous', 'olive green', 'pointed and slightly broader than their neck', 'checkered pattern all over the body in variation of green yellow or black', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(233, 'checkered keelback', 'non venomous', 'olive green', 'pointed and slightly broader than their neck', 'checkered pattern all over the body in variation of green yellow or black', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(234, 'checkered keelback', 'non venomous', 'yellow', 'pointed and slightly broader than their neck', 'checkered pattern all over the body in variation of green yellow or black', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(235, 'checkered keelback', 'non venomous', 'yellow', 'pointed and slightly broader than their neck', 'checkered pattern all over the body in variation of green yellow or black', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(236, 'green keelback or grass snake', 'non venomous', 'yellowish green', 'triangular and wide', 'viper like body with  keeled glossy scales', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(237, 'green keelback or grass snake', 'non venomous', 'yellowish green', 'triangular and wide', 'viper like body with  keeled glossy scales', 'round', 'itching', '0000-00-00 00:00:00', '1'),
(238, 'green keelback or grass snake', 'non venomous', 'yellowish green', 'triangular and wide', 'viper like body with  keeled glossy scales', 'round', 'redness', '0000-00-00 00:00:00', '1'),
(239, 'green keelback or grass snake', 'non venomous', 'yellowish green', 'triangular and wide', 'viper like body with  keeled glossy scales', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(240, 'green keelback or grass snake', 'non venomous', 'yellowish green', 'triangular and wide', 'viper like body with  keeled glossy scales', 'round', 'bleeding', '0000-00-00 00:00:00', '1'),
(241, 'striped keelback', 'non venomous', 'olive brown', 'triangular and curve', 'two yellow stripes along the body', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(242, 'striped keelback', 'non venomous', 'greyish', 'triangular and curve', 'two yellow stripes along the body', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(243, 'banded racer', 'non venomous', 'reddish brown', 'flattened', 'have smooth scales and yellowish or whitish belly', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(244, 'bronzeback tree snake', 'non venomous', 'bronze', 'flattened and elongated', 'thin long body covered with smooth scales', 'large round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(245, 'bronzeback tree snake', 'non venomous', 'brown', 'flattened and elongated', 'thin long body covered with smooth scales', 'large round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(246, 'bronzeback tree snake', 'non venomous', 'blackish brown', 'flattened and elongated', 'thin long body covered with smooth scales', 'large round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(247, 'boulengers bronze back', 'non venomous', 'blackish brown', 'flattened pear shaped', 'yellow lines margined by black dots run on the lateral sides of the body', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(248, 'boulengers bronze back', 'non venomous', 'copper', 'flattened pear shaped', 'yellow lines margined by black dots run on the lateral sides of the body', 'round', 'no symptoms', '0000-00-00 00:00:00', '1'),
(249, 'common wolf snake', 'non venomous', 'jet black', 'flattened and broader', 'smooth scales and white unmarked belly', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(250, 'common wolf snake', 'non venomous', 'jet black', 'flattened and broader', 'smooth scales and white unmarked belly', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(254, 'common wolf snake', 'non venomous', 'reddish brown', 'flattened and broader', 'smooth scales and white unmarked belly', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(255, 'common wolf snake', 'non venomous', 'reddish brown', 'flattened and broader', 'smooth scales and white unmarked belly', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(256, 'common wolf snake', 'non venomous', 'dark grey', 'flattened and broader', 'smooth scales and white unmarked belly', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(257, 'common wolf snake', 'non venomous', 'dark grey', 'flattened and broader', 'smooth scales and white unmarked belly', 'round', 'swelling', '0000-00-00 00:00:00', '1'),
(258, 'travancore wolf snake', 'non venomous', 'dark brown', 'flattened and broader', 'dark brown and black dorsally with white crossbands', 'invisible', 'minor pain', '0000-00-00 00:00:00', '1'),
(259, 'travancore wolf snake', 'non venomous', 'dark brown', 'flattened and broader', 'dark brown and black dorsally with white crossbands', 'invisible', 'swelling', '0000-00-00 00:00:00', '1'),
(260, 'travancore wolf snake', 'non venomous', 'black', 'flattened and broader', 'dark brown and black dorsally with white crossbands', 'invisible', 'minor pain', '0000-00-00 00:00:00', '1'),
(261, 'travancore wolf snake', 'non venomous', 'black', 'flattened and broader', 'dark brown and black dorsally with white crossbands', 'invisible', 'swelling', '0000-00-00 00:00:00', '1'),
(262, 'common banded kukri snake', 'non venomous', 'pale brown', 'large A shaped rostral', 'large A shaped rostral and distinct arrowhead', 'round', 'prolonged bleeding', '0000-00-00 00:00:00', '1'),
(263, 'common banded kukri snake', 'non venomous', 'orange', 'large A shaped rostral', 'large A shaped rostral and distinct arrowhead', 'round', 'prolonged bleeding', '0000-00-00 00:00:00', '1'),
(264, 'russells kukri snake', 'non venomous', 'reddish brown', 'arrow shaped marking present on the top of the head', 'glossy scales colored reddish brown on dorsal', 'round', 'minor pain', '0000-00-00 00:00:00', '1'),
(265, 'beddomes keelback', 'non venomous', 'yellowish brown', 'flattened', 'brown above a series of yellow spots', 'round', 'severe pain', '0000-00-00 00:00:00', '1'),
(266, 'beddomes keelback', 'non venomous', 'black', 'flattened', 'brown above a series of yellow spots', 'round', 'severe pain', '0000-00-00 00:00:00', '1');


ALTER TABLE `algo`
  ADD PRIMARY KEY (`iId`);


ALTER TABLE `algo`
  MODIFY `iId` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=266;
COMMIT;
