<?php
	$customer_config = array(
		'vName'=>array(
			'validate'=>'1',
			'clientname'=>'customerName',
			'type'=>'string',
			'other_validation'=>array('Valid_full_name','Space_between','Exist_bad_word')
		),
		'iCity'=>array(
			'validate'=>'1', 
			'clientname'=>'customerCity',
			'type'=>'array',
			'other_validation'=>array()
		),
		'iPhoneCode'=>array(
			'validate'=>'1',
			'clientname'=>'customerCountryCode',
			'type'=>'number',
			'other_validation'=>array()
		),
		'iContactNo'=>array(
			'validate'=>'1',
			'clientname'=>'customerContactNo',
			'type'=>'string',
			'other_validation'=>array(
				'valid_phone_number'
			)
		),
		'vAddress'=>array(
			'validate'=>'1',
			'clientname'=>'customerAddress',
			'type'=>'string',
			'other_validation'=>array(
				'Exist_bad_word'
			)
		),
		'vEmail'=>array(
			'validate'=>'1',
			'clientname'=>'customerEmail',
			'type'=>'string',
			'other_validation'=>array(
				'Exist_bad_word','valid_email_address','email_exist'
			)
		),
		'vPassword'=>array(
			'validate'=>'1',
			'clientname'=>'customerPassword',
			'type'=>'string',
			'other_validation'=>array(
				'compare_with_password'
			)
		),
		'vImage'=>array(
			'validate'=>'0',
			'clientname'=>'customerImage',
			'type'=>'string',
			'other_validation'=>array()
		),
		'vUnit'=>array(
			'validate'=>'1',
			'clientname'=>'customerUnit',
			'type'=>'string',
			'other_validation'=>array()
		),
		'dRegistrationDate'=>array(
			'validate'=>'1',
			'clientname'=>'customerRegistrationDate',
			'type'=>'date',
			'other_validation'=>array()
		),
		'vStatus'=>array(
			'validate'=>'1',
			'clientname'=>'customerStatus',
			'type'=>'string',
			'other_validation'=>array()
		)
	)	
?>